### ISSUE TITLE
0.3.0 版本 border 不显示

### ISSUE THREAD

**Issue by MellowCo** [MellowCo/unocss-preset-weapp#25]
```html
<view class="border-red-500 border-4">
   border-red-500 border-4
</view>
```

![image](https://user-images.githubusercontent.com/47939250/209419779-5ec88721-d029-4f2d-a9f2-5464f9725c85.png)

**Comment by MellowCo** [comment]
因为 border 中移除了 border-style:solid; 详细提交说明见 [1971](https://github.com/unocss/unocss/pull/1971)
![image](https://user-images.githubusercontent.com/47939250/209420999-989e4e25-a61b-4b88-b5d1-dacf13fbaf07.png)

**Comment by MellowCo** [comment]
方法一： 添加 `b-solid` 类名

```html
<view class="border-red-500 border-4 b-solid">
   border-red-500 border-4
</view>
```

**Comment by MellowCo** [comment]
方法二: 设置全局 preset

```css
view,:before,:after {
  border-width: 0;
  border-style: solid;
  border-color: #e5e7eb
}
```
